[tool.pytest.ini_options]
django_debug_mode = true
DJANGO_SETTINGS_MODULE = "config.settings"
testpaths = [
    "tests",
]
python_files = ["test_*.py"]
# addopts = "-n auto"
addopts = "-n auto --cov=pages --cov=records --cov-report=term"

[tool.coverage.run]
source = ["."]
omit = [
    "config/*",
    "manage.py",
    ".venv/*",
    "tests/*",
    "records/migrations/*",
    "__init__.py"
    ]

[tool.coverage.report]
fail_under = 83
show_missing = true
skip_covered = true
sort = "Miss"
precision = 1