services:
- type: web
  name: logaday-django
  env: python
  plan: free
  buildCommand: ./build.sh
  startCommand: gunicorn config.wsgi:application
  autoDeploy: false
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.2
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: dblad
        property: connectionString
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings
    - key: DJANGO_DEBUG
      value: false
    - key: DJANGO_ALLOWED_HOSTS
      value: "logaday-django.onrender.com"

databases:
- name: dblad
  plan: free
  databaseName: dblad
  user: dblad
