# Generated by Django 4.1.7 on 2023-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="log_sections",
            field=models.CharField(
                default="personal, work",
                help_text="Required. Comma separated list of default sections for logs",
                max_length=300,
                verbose_name="log sections",
            ),
        ),
    ]
