# Generated by Django 4.1.7 on 2023-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsetting",
            name="headings",
            field=models.CharField(
                blank=True,
                default="personal, work",
                help_text="Required. Comma separated list of default headings to use.",
                max_length=300,
                verbose_name="record headings",
            ),
        ),
    ]
