# Generated by Django 4.1.7 on 2023-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_alter_recordsetting_headings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="record",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="title"),
        ),
    ]
